name: bench

on: [pull_request]

jobs:
  bench:
    name: bench
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Download and install critcmp
        run: cargo install critcmp
      - name: Run bench on current branch
        run: cargo bench -p rstml --bench bench -- --save-baseline changes
      - name: Run bench on main branch
        run: |
          git checkout main
          cargo bench -p rstml --bench bench -- --save-baseline main
      - name: Compare the results
        run: critcmp main changes
