name: coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: coverage nightly
        run: |
            cargo install cargo-tarpaulin
            cargo tarpaulin --out xml --output-dir ./nightly --workspace
      - uses: dtolnay/rust-toolchain@stable

      - name: coverage nightly
        run: |
            cargo tarpaulin --out xml --output-dir ./stable --workspace
      - uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./stable/cobertura.xml,./nightly/cobertura.xml 
            name: RSTML